In [1]:
pip install scikit-image

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [4]:
from skimage.feature import hog
from skimage import data ,exposure

# READING IMG

In [22]:
img_1 = cv2.imread("C:\\Users\\aedpu\Downloads\\car6.jpg")

In [23]:
img_1

array([[[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [204, 204, 204],
        [204, 204, 204],
        [204, 204, 204]],

       [[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [204, 204, 204],
        [204, 204, 204],
        [204, 204, 204]],

       [[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [204, 204, 204],
        [204, 204, 204],
        [204, 204, 204]],

       ...,

       [[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [217, 217, 217],
        [192, 192, 192],
        [214, 214, 214]],

       [[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [196, 196, 196],
        [202, 202, 202],
        [200, 200, 200]],

       [[204, 204, 204],
        [204, 204, 204],
        [204, 204, 204],
        ...,
        [214, 214, 214],
        [177, 177, 177],
        [220, 220, 220]]

In [24]:
img = cv2.resize(img_1,(512,512))

In [25]:
cv2.imshow('original',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
featdis , hog_image = hog(img , pixels_per_cell = (3 , 3 ),
                         cells_per_block = (60, 60 ) , visualize = True ,channel_axis= 2)

In [30]:
print(featdis)

[0.         0.         0.         ... 0.00047335 0.         0.00069214]


In [34]:
cv2.imshow('hog',hog_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Rescaling

In [32]:
rescale = exposure.rescale_intensity(hog_image, in_range=(0,1))

In [33]:
rescale

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# plot